# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af078573a8938b40637e7bd63990d4830aedc54d05b619c0dabe2093e647c26daf11803abc611c262eb9519c7a4e5b4204dcee17d79202ef2167344d0cd1c06e

test:
  secret_key_base: e19785737c97a1f10db5df5a74e8af63a57a96650843b418274ead0de97d8252e3af6ecc48bc041b519f55a5937d6ed8b300e91e27f600a0d245be0aca3a7125

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
